Repository omou-org/front-end, pull requests merged in 2020-03, with the labels that each got.

#272 Ooo display
  src/actions/actionTypes.js
  src/actions/authActions.js
  src/actions/hooks.js
  src/actions/userActions.js
  src/components/FeatureViews/Accounts/ComponentViewer.js
  src/components/FeatureViews/Accounts/OutOfOffice.js
  src/components/FeatureViews/Accounts/TabComponents/InstructorSchedule.js
  src/components/FeatureViews/Registration/RegistrationCourse.js
  src/components/FeatureViews/Scheduler/DisplaySessionView.js
  src/components/FeatureViews/Scheduler/Scheduler.js
  src/components/FeatureViews/Search/cards/AccountsCards.js
  src/components/truncateStrings.js
  src/reducers/usersReducer.js
  src/utils.js
Labels: enhancement

#273 session_payment_status
  package-lock.json
  package.json
  src/AddSessions.js
  src/App.scss
  src/actions/apiActions.js
  src/components/FeatureViews/Accounts/Accounts.js
  src/components/FeatureViews/Accounts/ComponentViewer.js
  src/components/FeatureViews/Accounts/OutOfOffice.js
  src/components/FeatureViews/Accounts/ProfileHeading.js
  src/components/FeatureViews/Accounts/TabComponents/EnrollmentView.js
  src/components/FeatureViews/Accounts/TabComponents/StudentCourseViewer.js
  src/components/FeatureViews/Accounts/TabComponents/TabComponents.scss
  src/components/FeatureViews/Registration/CourseList.js
  src/components/FeatureViews/Registration/Registration.js
  src/components/FeatureViews/Registration/RegistrationCourseEnrollments.js
  src/components/FeatureViews/Scheduler/DisplaySessionView.js
  src/components/FeatureViews/Scheduler/EditSessionView.js
  src/components/Loading.js
  src/components/Navigation/Navigation.js
  src/components/Navigation/Navigation.scss
  src/components/NoListAlert.js
  src/components/Routes/RootRoutes.js
  src/components/Routes/rootRoutes.js
  src/components/SessionPaymentStatusChip.js
  src/reducers/enrollmentReducer.js
  src/theme/_colors.scss
  src/utils.js
Labels: enhancement

#286 Instructor conflict
  src/actions/hooks.js
  src/components/FeatureViews/Scheduler/EditSessionView.js
  src/components/InstructorConflictCheck.js
  src/utils.js
Labels: enhancement

#288 Fix registration loading bug
  src/components/FeatureViews/Registration/RegistrationLanding.js
Labels: bug

#290 Instructor conflict
  src/components/FeatureViews/Registration/RegistrationLanding.js
  src/components/Form/Form.js
  src/components/InstructorConflictCheck.js
  src/utils.js
Labels: enhancement

#297 Note Badge + Unpaid Session Fix
  src/components/FeatureViews/Accounts/TabComponents/ParentContact.js
  src/components/FeatureViews/Accounts/TabComponents/PaymentHistory.js
  src/components/FeatureViews/Accounts/TabComponents/StudentCourseViewer.js
  src/components/FeatureViews/Accounts/UserProfile.js
  src/components/FeatureViews/AdminPortal/UnpaidSessions.js
  src/components/FeatureViews/Notes/Notes.js
  src/components/FeatureViews/Registration/registration.scss
  src/theme/muiTheme.js
  src/utils.js
Labels: 1 Hour

#307 Notes update
  src/actions/actionTypes.js
  src/components/FeatureViews/Accounts/TabComponents/TabComponents.scss
  src/components/FeatureViews/Notes/Notes.js
  src/components/FeatureViews/Notes/Notes.scss
  src/reducers/courseReducer.js
  src/reducers/enrollmentReducer.js
  src/reducers/usersReducer.js
Labels: enhancement

#325 Update login test
  cypress.json
  cypress/integration/A_000Login_spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/components/Authentication/LoginPage.js
  src/components/Authentication/LoginPage.scss
  src/index.js
Labels: enhancement

#310 modified error loading courses
  .env.local
  src/components/FeatureViews/Accounts/TabComponents/EnrollmentView.js
  src/components/FeatureViews/Accounts/TabComponents/InstructorCourses.js
  src/components/FeatureViews/Accounts/TabComponents/LoadingCourseError.js
  src/components/FeatureViews/Accounts/TabComponents/ParentContact.js
  src/components/FeatureViews/Accounts/TabComponents/StudentCourseViewer.js
  src/components/FeatureViews/Accounts/TabComponents/StudentInfo.js
  src/components/FeatureViews/Accounts/TabComponents/loadingCoursesError.png
  src/components/FeatureViews/Notes/Notes.js
  src/components/FeatureViews/Registration/RegistrationCourseEnrollments.js
  src/components/FeatureViews/Registration/TutoringList.js
  src/components/FeatureViews/Scheduler/DisplaySessionView.js
Labels: enhancement
